const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="saimsamsun789@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://github.com/SuhailTechInfo/Suhail-Md/blob/main/lib/assets/suhail.jpg?raw=true" ; // SET LOGO FOR IMAGE 



global.devs = "94769482229" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923184474176";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_03_07_04_25_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTYwLFxuICAgICAgICAxODcsXG4gICAgICAgIDEzNixcbiAgICAgICAgMTM2LFxuICAgICAgICAyMDUsXG4gICAgICAgIDE4MyxcbiAgICAgICAgMTE0LFxuICAgICAgICAxNDIsXG4gICAgICAgIDIzMSxcbiAgICAgICAgMTA4LFxuICAgICAgICAzOSxcbiAgICAgICAgMjQyLFxuICAgICAgICAxOCxcbiAgICAgICAgMjEzLFxuICAgICAgICAxOTIsXG4gICAgICAgIDE4LFxuICAgICAgICA4MSxcbiAgICAgICAgMTExLFxuICAgICAgICAxNDMsXG4gICAgICAgIDIzNixcbiAgICAgICAgMTQwLFxuICAgICAgICAyNDIsXG4gICAgICAgIDkzLFxuICAgICAgICA2OSxcbiAgICAgICAgNTIsXG4gICAgICAgIDcxLFxuICAgICAgICAxMTMsXG4gICAgICAgIDIyMyxcbiAgICAgICAgMjAsXG4gICAgICAgIDEwNixcbiAgICAgICAgMTY0LFxuICAgICAgICAxMDNcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMzYsXG4gICAgICAgIDEwMyxcbiAgICAgICAgMjA1LFxuICAgICAgICA2NixcbiAgICAgICAgMTcsXG4gICAgICAgIDE5MCxcbiAgICAgICAgMSxcbiAgICAgICAgODksXG4gICAgICAgIDI1MixcbiAgICAgICAgMjExLFxuICAgICAgICAxNjEsXG4gICAgICAgIDExMixcbiAgICAgICAgMTUwLFxuICAgICAgICAyMzUsXG4gICAgICAgIDE5NixcbiAgICAgICAgNDksXG4gICAgICAgIDQ4LFxuICAgICAgICAyMTksXG4gICAgICAgIDIwMyxcbiAgICAgICAgMjMyLFxuICAgICAgICAxNDYsXG4gICAgICAgIDM5LFxuICAgICAgICAxODUsXG4gICAgICAgIDIwNyxcbiAgICAgICAgOTIsXG4gICAgICAgIDQ2LFxuICAgICAgICAxMDAsXG4gICAgICAgIDEzOSxcbiAgICAgICAgMTc4LFxuICAgICAgICAxNDMsXG4gICAgICAgIDExMCxcbiAgICAgICAgMlxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTg0LFxuICAgICAgICA2OSxcbiAgICAgICAgNTUsXG4gICAgICAgIDE5MCxcbiAgICAgICAgNjYsXG4gICAgICAgIDIzMyxcbiAgICAgICAgMTk4LFxuICAgICAgICAzLFxuICAgICAgICAxMTAsXG4gICAgICAgIDExMixcbiAgICAgICAgMjI0LFxuICAgICAgICAyNSxcbiAgICAgICAgNDMsXG4gICAgICAgIDE0NCxcbiAgICAgICAgMTY5LFxuICAgICAgICAxMDMsXG4gICAgICAgIDE3NCxcbiAgICAgICAgMTg0LFxuICAgICAgICAxMTMsXG4gICAgICAgIDM4LFxuICAgICAgICAzMyxcbiAgICAgICAgODcsXG4gICAgICAgIDE0MSxcbiAgICAgICAgODQsXG4gICAgICAgIDIzNixcbiAgICAgICAgMjM1LFxuICAgICAgICA5NCxcbiAgICAgICAgMjI5LFxuICAgICAgICAyMjMsXG4gICAgICAgIDE1MixcbiAgICAgICAgOCxcbiAgICAgICAgNjlcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTI3LFxuICAgICAgICAxNjAsXG4gICAgICAgIDU5LFxuICAgICAgICAxNjIsXG4gICAgICAgIDEwOCxcbiAgICAgICAgMTQ5LFxuICAgICAgICAyMDAsXG4gICAgICAgIDQsXG4gICAgICAgIDMwLFxuICAgICAgICA5MSxcbiAgICAgICAgNjcsXG4gICAgICAgIDEzLFxuICAgICAgICAyMjksXG4gICAgICAgIDExMSxcbiAgICAgICAgOTQsXG4gICAgICAgIDE5OSxcbiAgICAgICAgODcsXG4gICAgICAgIDIwMyxcbiAgICAgICAgMzAsXG4gICAgICAgIDE1MSxcbiAgICAgICAgMjQxLFxuICAgICAgICAxNzksXG4gICAgICAgIDIwNixcbiAgICAgICAgMTA3LFxuICAgICAgICAyNTAsXG4gICAgICAgIDQwLFxuICAgICAgICA1MCxcbiAgICAgICAgMjYsXG4gICAgICAgIDI0NixcbiAgICAgICAgMjA5LFxuICAgICAgICAxNjEsXG4gICAgICAgIDUwXG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA5NixcbiAgICAgICAgMTMsXG4gICAgICAgIDE2NCxcbiAgICAgICAgMTMxLFxuICAgICAgICAyNTQsXG4gICAgICAgIDE1OSxcbiAgICAgICAgMTI0LFxuICAgICAgICAxODQsXG4gICAgICAgIDE5MyxcbiAgICAgICAgNzcsXG4gICAgICAgIDEwNCxcbiAgICAgICAgMjI1LFxuICAgICAgICAzMCxcbiAgICAgICAgMTMyLFxuICAgICAgICAyMDQsXG4gICAgICAgIDEyOSxcbiAgICAgICAgMjI5LFxuICAgICAgICAxNjgsXG4gICAgICAgIDEwNyxcbiAgICAgICAgMTY5LFxuICAgICAgICAyMzAsXG4gICAgICAgIDk3LFxuICAgICAgICAyMTIsXG4gICAgICAgIDE0LFxuICAgICAgICAyMTIsXG4gICAgICAgIDIxMixcbiAgICAgICAgMTg3LFxuICAgICAgICA5MyxcbiAgICAgICAgMTE2LFxuICAgICAgICAxNTAsXG4gICAgICAgIDU4LFxuICAgICAgICAxMDFcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTgwLFxuICAgICAgICAyMTQsXG4gICAgICAgIDcsXG4gICAgICAgIDE2MixcbiAgICAgICAgMTExLFxuICAgICAgICA0NixcbiAgICAgICAgOTcsXG4gICAgICAgIDEzNyxcbiAgICAgICAgMTM3LFxuICAgICAgICAzMyxcbiAgICAgICAgODQsXG4gICAgICAgIDYwLFxuICAgICAgICAyMCxcbiAgICAgICAgMTE2LFxuICAgICAgICAzNSxcbiAgICAgICAgMTA1LFxuICAgICAgICAxNTMsXG4gICAgICAgIDE3MSxcbiAgICAgICAgMzgsXG4gICAgICAgIDEwNCxcbiAgICAgICAgNDUsXG4gICAgICAgIDIwMyxcbiAgICAgICAgMTAxLFxuICAgICAgICAzMCxcbiAgICAgICAgNjUsXG4gICAgICAgIDIxMixcbiAgICAgICAgMTE4LFxuICAgICAgICAyNDQsXG4gICAgICAgIDQ4LFxuICAgICAgICAxNDgsXG4gICAgICAgIDk2LFxuICAgICAgICAxMDJcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgOTYsXG4gICAgICAgICAgMTIyLFxuICAgICAgICAgIDI0LFxuICAgICAgICAgIDUsXG4gICAgICAgICAgNjQsXG4gICAgICAgICAgMjEsXG4gICAgICAgICAgNDgsXG4gICAgICAgICAgMjI4LFxuICAgICAgICAgIDE5LFxuICAgICAgICAgIDIyMyxcbiAgICAgICAgICAxMzMsXG4gICAgICAgICAgMjAwLFxuICAgICAgICAgIDIyNixcbiAgICAgICAgICAyMjIsXG4gICAgICAgICAgMTg2LFxuICAgICAgICAgIDE1MixcbiAgICAgICAgICA2NCxcbiAgICAgICAgICA4OCxcbiAgICAgICAgICAxOTIsXG4gICAgICAgICAgMjI1LFxuICAgICAgICAgIDExOCxcbiAgICAgICAgICAyMjUsXG4gICAgICAgICAgMjM1LFxuICAgICAgICAgIDk4LFxuICAgICAgICAgIDAsXG4gICAgICAgICAgMjQ4LFxuICAgICAgICAgIDEzNCxcbiAgICAgICAgICAxMDIsXG4gICAgICAgICAgMjI2LFxuICAgICAgICAgIDExNixcbiAgICAgICAgICA3MCxcbiAgICAgICAgICA3M1xuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxOCxcbiAgICAgICAgICA1NSxcbiAgICAgICAgICAxMjYsXG4gICAgICAgICAgMjIsXG4gICAgICAgICAgMTU3LFxuICAgICAgICAgIDIzOCxcbiAgICAgICAgICA4MyxcbiAgICAgICAgICAyMzcsXG4gICAgICAgICAgMTc0LFxuICAgICAgICAgIDE2MyxcbiAgICAgICAgICAxMjksXG4gICAgICAgICAgMTE4LFxuICAgICAgICAgIDIxNixcbiAgICAgICAgICA3OSxcbiAgICAgICAgICAzMixcbiAgICAgICAgICAxMDUsXG4gICAgICAgICAgMTk4LFxuICAgICAgICAgIDE3LFxuICAgICAgICAgIDE3NyxcbiAgICAgICAgICA5NyxcbiAgICAgICAgICAxMzUsXG4gICAgICAgICAgNTMsXG4gICAgICAgICAgMTcxLFxuICAgICAgICAgIDY4LFxuICAgICAgICAgIDMwLFxuICAgICAgICAgIDg2LFxuICAgICAgICAgIDE4MyxcbiAgICAgICAgICAzMSxcbiAgICAgICAgICA4NSxcbiAgICAgICAgICAxMCxcbiAgICAgICAgICAxMzUsXG4gICAgICAgICAgNjBcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMDEsXG4gICAgICAgIDE1MCxcbiAgICAgICAgMjA4LFxuICAgICAgICAyMjYsXG4gICAgICAgIDgyLFxuICAgICAgICAyMDMsXG4gICAgICAgIDEsXG4gICAgICAgIDI0NixcbiAgICAgICAgMTI4LFxuICAgICAgICAxMTIsXG4gICAgICAgIDU2LFxuICAgICAgICAyNixcbiAgICAgICAgOSxcbiAgICAgICAgMjI5LFxuICAgICAgICA3LFxuICAgICAgICAyMzAsXG4gICAgICAgIDEzMSxcbiAgICAgICAgMTY1LFxuICAgICAgICAxMTQsXG4gICAgICAgIDI1MCxcbiAgICAgICAgMTc4LFxuICAgICAgICAxODcsXG4gICAgICAgIDYwLFxuICAgICAgICAyMTUsXG4gICAgICAgIDIyMyxcbiAgICAgICAgMTY3LFxuICAgICAgICAxNTYsXG4gICAgICAgIDI3LFxuICAgICAgICAyOSxcbiAgICAgICAgNDgsXG4gICAgICAgIDIzNixcbiAgICAgICAgMTc3LFxuICAgICAgICAxMTksXG4gICAgICAgIDE4OSxcbiAgICAgICAgMjUsXG4gICAgICAgIDQxLFxuICAgICAgICAxMDEsXG4gICAgICAgIDUsXG4gICAgICAgIDE5LFxuICAgICAgICAyMDYsXG4gICAgICAgIDUyLFxuICAgICAgICAxNzcsXG4gICAgICAgIDEwMCxcbiAgICAgICAgMTUzLFxuICAgICAgICAyOCxcbiAgICAgICAgMCxcbiAgICAgICAgMTE4LFxuICAgICAgICAxNDYsXG4gICAgICAgIDEzNSxcbiAgICAgICAgMjE5LFxuICAgICAgICAxMTMsXG4gICAgICAgIDExMixcbiAgICAgICAgMjEsXG4gICAgICAgIDI1NSxcbiAgICAgICAgMjE4LFxuICAgICAgICA0MixcbiAgICAgICAgMjA4LFxuICAgICAgICAyMDcsXG4gICAgICAgIDIzNixcbiAgICAgICAgNzMsXG4gICAgICAgIDEzMSxcbiAgICAgICAgMTc1LFxuICAgICAgICAyMTAsXG4gICAgICAgIDEzMFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogOTIsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwicGZoaTZlZDYyZzBBWGl5WncwbzZidXNWM2xKaXZBNmZNUFlHOWg2dzhQZz1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW1xuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCI5NDcwMzA3NzkzN0BzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiMDU5MTdFMkM1QTEwNjcxRjAxNkNDRUM5OEEwOEMwMzJcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzE0MDE0NDI2XG4gICAgfSxcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiOTQ3MDMwNzc5MzdAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjA2MTMwOUY0MDY5RDREN0ZDODJERTA0OERFQkVBMDI1XCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcxNDAxNDQyNlxuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjk0NzAzMDc3OTM3QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCI3M0MxOTVEQTIzOTcxRUMyNDA1ODY4Mjg0NDIwNEVFOVwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MTQwMTQ0MjlcbiAgICB9LFxuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCI5NDcwMzA3NzkzN0BzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiQjRFOTdFNkE0MjUwRTg1NDY4N0ZEMTk4RjUxQ0Y5QTZcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzE0MDE0NDI5XG4gICAgfVxuICBdLFxuICBcIm5leHRQcmVLZXlJZFwiOiAzMSxcbiAgXCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZFwiOiAzMSxcbiAgXCJhY2NvdW50U3luY0NvdW50ZXJcIjogMSxcbiAgXCJhY2NvdW50U2V0dGluZ3NcIjoge1xuICAgIFwidW5hcmNoaXZlQ2hhdHNcIjogZmFsc2VcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcIndiMVA3cC00UnJ1bXNZTFVtSG9DaUFcIixcbiAgXCJwaG9uZUlkXCI6IFwiMDY1MjY4YWItY2EzZS00YjMzLWI5YjctOTE0YzYyNGNlY2ZkXCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDIxLFxuICAgICAgMzYsXG4gICAgICA0MyxcbiAgICAgIDQ2LFxuICAgICAgMTUzLFxuICAgICAgMjEyLFxuICAgICAgMTczLFxuICAgICAgMTE2LFxuICAgICAgMjAwLFxuICAgICAgMTEsXG4gICAgICA3NixcbiAgICAgIDE3MSxcbiAgICAgIDExNyxcbiAgICAgIDE2LFxuICAgICAgMTI1LFxuICAgICAgMTU1LFxuICAgICAgMTE5LFxuICAgICAgMTc1LFxuICAgICAgMjM4LFxuICAgICAgMTc0XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogZmFsc2UsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAxMzMsXG4gICAgICAxMjQsXG4gICAgICAxNDIsXG4gICAgICA0MyxcbiAgICAgIDY5LFxuICAgICAgNzgsXG4gICAgICAxNTAsXG4gICAgICAxOTYsXG4gICAgICA3MCxcbiAgICAgIDE4NSxcbiAgICAgIDU3LFxuICAgICAgMzEsXG4gICAgICAxNjAsXG4gICAgICA5MCxcbiAgICAgIDEyNSxcbiAgICAgIDQ5LFxuICAgICAgMTkxLFxuICAgICAgMjM1LFxuICAgICAgMTE1LFxuICAgICAgMTE0XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDTnlYcGRjREVOU1JwN0VHR0FFZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJoZXRtbG43Qk56RjRIN1cvT1dCV3MxT2VhdXdIWmhUVWVhdXBFc3pLODFzPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcIjNMb1BDYXhpWUFHQTIvNHZpTkRwaWNEbFIwbFdKZjA0RGNtNEZPR0R4SWhsVm1OT2luVlJib2JWK0hwZmdJU1JvMGNIaFRPak82VUtTNG8rSlBpSkRBPT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcIkJ0WGhjUHBDR0diZzAzV0FvUm0ydWxuMndjMlNydlhSN0FWMDdnMjA2QmgxUlI4RGtDTHUrYUx0THluMXp5OXYzcm9SWUFMQk5ZTDU0ZmM5TndyMWl3PT1cIlxuICB9LFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiOTQ3MDMwNzc5Mzc6MTJAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcImxpZFwiOiBcIjY0Mjg3NTczODI3NzQ1OjEyQGxpZFwiLFxuICAgIFwibmFtZVwiOiBcIkhpcmFuIEJyb1wiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiOTQ3MDMwNzc5Mzc6MTJAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICAxMzMsXG4gICAgICAgICAgMjM1LFxuICAgICAgICAgIDEwMixcbiAgICAgICAgICAxNTAsXG4gICAgICAgICAgMTI2LFxuICAgICAgICAgIDE5MyxcbiAgICAgICAgICA1NSxcbiAgICAgICAgICA0OSxcbiAgICAgICAgICAxMjAsXG4gICAgICAgICAgMzEsXG4gICAgICAgICAgMTgxLFxuICAgICAgICAgIDE5MSxcbiAgICAgICAgICA1NyxcbiAgICAgICAgICA5NixcbiAgICAgICAgICA4NixcbiAgICAgICAgICAxNzksXG4gICAgICAgICAgODMsXG4gICAgICAgICAgMTU4LFxuICAgICAgICAgIDEwNixcbiAgICAgICAgICAyMzYsXG4gICAgICAgICAgNyxcbiAgICAgICAgICAxMDIsXG4gICAgICAgICAgMjAsXG4gICAgICAgICAgMjEyLFxuICAgICAgICAgIDEyMSxcbiAgICAgICAgICAxNzEsXG4gICAgICAgICAgMTY5LFxuICAgICAgICAgIDE4LFxuICAgICAgICAgIDIwNCxcbiAgICAgICAgICAyMDIsXG4gICAgICAgICAgMjQzLFxuICAgICAgICAgIDkxXG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJhbmRyb2lkXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MTQwMTQ0MjMsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFBZlpcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUFmWi5qc29uIjogIntcImtleURhdGFcIjpcIjIxVmRPVTl4WGViK3JWbHlIN05aUnJVYnNqSHJqQjltK3VlQ25MeFJjd2M9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6OTg4MzY3ODM0LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFBZmEuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJENE1MVDNhcTJabVhrL3pUMlpsM0p5QW1PV1J1STFiTHczbGlpTGpReFM0PVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjk4ODM2NzgzNCxcImN1cnJlbnRJbmRleFwiOjIsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIxNzEzOTcwMTY1NDQ3XCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBQWZiLmpzb24iOiAie1wia2V5RGF0YVwiOlwiNUh6SW9HM2t4K3M2MzdiS0JmNENjYndRK3gwQWpMUEF1V0wrbE53aVlkND1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjo5ODgzNjc4MzUsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUFmYy5qc29uIjogIntcImtleURhdGFcIjpcIkJEWmJ6d2ticlhwYUl4VTJRTTJqMVFoM012ZFQxQy9ZcW80T0crV1JUS3M9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6OTg4MzY3ODM1LFwiY3VycmVudEluZGV4XCI6MixcImRldmljZUluZGV4ZXNcIjpbMCwyXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MTQwMTM1MjQ3MzFcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFBZmQuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJqSnBMWm5rcUNRTGNXOG5ZNDNGZjNTTUtSdXRoZTllODFhSVl3anMzam9NPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjk4ODM2NzgzNSxcImN1cnJlbnRJbmRleFwiOjIsXCJkZXZpY2VJbmRleGVzXCI6WzBdfSxcInRpbWVzdGFtcFwiOlwiMTcxNDAxMzUzNDY4OFwifSIKfQ=="  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.4",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "private",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
